spring.application.name=finance-system

# H2 database 設定
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=esun
spring.datasource.password=esun

# 啟用 H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 啟動時執行 SQL
spring.sql.init.mode=always

# 顯示 SQL
#spring.jpa.show-sql=true